[project]
name = "income-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ParthChandel165", email = "parth.chandel20@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "openpyxl>=3.1.5",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
]

[project.scripts]
income-analysis = "income_analysis:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
